### ISSUE TITLE
Can't control from outside component. 

### ISSUE THREAD

**Issue by repolife** [BTMPL/react-yt#2]
Do you have an example of controlling the props from the outside?

**Comment by BTMPL** [comment]
The component is not really created with that in mind, having said that, you technically can controll it from outside, by re-rendering and haing the render function be impure, e.g.

```
class ControlledYoutube extends React.PureComponent {
  render() {
    return (
      <YouTube
        videoId={'SKGzIhOSQVY'}
        render={({
          iframe,
          playVideo,
          pauseVideo,
          getPlayerState
        }) => {
          if (this.props.isPlaying) playVideo();
          else pauseVideo();
          return null;
        }
      />
    )
  }
}
```

and then using it as `<ControlledYoutube isPlaying={true} />` etc. You just need to make sure that the component does not re-render when props don't change or at least don't call the functions like `nextVideo` or `loadVideoById` when the value that controls them has not changed.

An alternative would be accessing the component itself as a ref, and using `ref.proxyToPlayer` but that's even dirtier.
